### ISSUE TITLE
internal/include/jemalloc/internal/jemalloc_internal_decls.h:21:14: fatal error: 'os/lock.h' file not found

### ISSUE THREAD

**Issue by glycerine** [cockroachdb/c-jemalloc#10]
I pulled master of c-jemalloc, on OSX 10.11.6, but it doesn't seem to build...

~~~
jaten@jatens-MacBook-Pro ~/go/src/github.com/cockroachdb/c-jemalloc (master) $ go install
go install
# github.com/cockroachdb/c-jemalloc
In file included from ./arena.c:2:
In file included from darwin_includes/internal/include/jemalloc/internal/jemalloc_internal.h:5:
internal/include/jemalloc/internal/jemalloc_internal_decls.h:21:14: fatal error: 'os/lock.h' file not found
jaten@jatens-MacBook-Pro ~/go/src/github.com/cockroachdb/c-jemalloc (master) $ 
~~~

**Comment by glycerine** [comment]
possibly related to https://github.com/jemalloc/jemalloc/issues/502

**Comment by glycerine** [comment]
the compile trace in the first comment of https://github.com/harbour/core/issues/128  makes me think that os/lock.h may have been introduced in OSX 10.12.

`../../../../../include/hbatomic.h:477:10: warning: 'OSSpinLock' is deprecated: first deprecated in macOS 10.12 - Use os_unfair_lock() from <os/lock.h>`

**Comment by glycerine** [comment]
confirmed, from: https://github.com/jemalloc/jemalloc/issues/494

**Comment by glycerine** [comment]
the workaround mentioned in https://github.com/jemalloc/jemalloc/issues/494 , namely `export je_cv_os_unfair_lock=no` does seem to work for me.

**Comment by bdarnell** [comment]
I can confirm this behavior as well. Note that cockroachdb is not using this repo's `master` yet; we're still on 42e6a32cd, which doesn't have this problem.
