### ISSUE TITLE
LibRT requirement breaks macOS build

### ISSUE THREAD

**Issue by yusefnapora** [cockroachdb/c-jemalloc#17]
The change to the `LDFLAGS` from https://github.com/cockroachdb/c-jemalloc/commit/6591f09d13d113e77c515230ad5ac64173698793 breaks compilation on macOS, since librt doesn't exist on that platform.

When trying to build c-rocksdb on a mac, I get the following:

```
$ go get github.com/cockroachdb/c-rocksdb
# github.com/cockroachdb/c-jemalloc
ld: library not found for -lrt
```

A solution would be to change the definition to

```go
// #cgo darwin LDFLAGS: -lm -lpthread
// #cgo !darwin LDFLAGS: -lm -lpthread -lrt
```

That's the approach used by gorocksdb here: https://github.com/tecbot/gorocksdb/blob/master/embedflag.go

I believe the underlying functionality from librt is included in libSystem on a mac, so the linker phase still succeeds.

**Comment by tamird** [comment]
Hehe, I just opened #16.

**Comment by yusefnapora** [comment]
Awesome!  That was fast 😄
