### ISSUE TITLE
Failed to build in CentOS 7

### ISSUE THREAD

**Issue by bluesalt** [cockroachdb/c-jemalloc#8]
[Latest Master branch](https://github.com/cockroachdb/c-jemalloc/commit/f2755b08090c954a7de3addde2a8ed009607dbe9) failed to build in CentOS 7. Here is the output

```
# github.com/cockroachdb/c-jemalloc
In file included from ./arena.c:2:0:
linux_includes/internal/include/jemalloc/internal/jemalloc_internal.h:146:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.
```

Operating System:  `CentOS Linux release 7.2.1511 (Core) `
Kernel Version: `3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
gcc:  `gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)`

**Comment by tamird** [comment]
Looks like you need GCC 4.9 or higher. See
https://gcc.gnu.org/gcc-4.9/changes.html.

**Comment by tamird** [comment]
Going to close this - please let us know if the problem persists.

**Comment by monacv** [comment]
using this command solved the problem for me:
`scl enable devtoolset-7 bash`
